[project]
name = "13-all-books"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "curl-cffi>=0.13.0",
    "pandas>=2.3.2",
]
